sonar.projectKey=MelyzzHF_PasteleriaSanJuana
sonar.organization=melyzzhf

sonar.sources=frontend,backend

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js,frontend/package*.json,backend/package*.json, **/coverage/**
# Ruta al reporte de cobertura (ajusta si tus pruebas están en el frontend o backend)
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info