sonar.projectKey=MelyzzHF_PasteleriaSanJuana
sonar.organization=melyzzhf

sonar.sources=frontend,backend

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js,frontend/package*.json,backend/package*.json
